<?xml version="1.0" encoding="utf-8"?>
<Project>

  <!-- Import the solution .targets file. -->
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props"/>

  <!-- Import the shared src .targets file -->
  <Import Project="$(FreeDotnetSolutionDirectory)msbuild\targets\FreeDotnet.Src.targets"/>

</Project>
