<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <!--Disable config copy. This solution only.-->
    <FreeDotnetDisableConfigCopy>true</FreeDotnetDisableConfigCopy>
  </PropertyGroup>

  <!-- Import the shared tests .props file -->
  <Import Project="$(MSBuildThisFileDirectory)..\msbuild\props\FreeDotnet.Tests.props"/>
  
  <!-- Import the solution .props file. -->
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props"/>

</Project>
