<?xml version="1.0" encoding="utf-8"?>
<Project>

  <!-- Compilation and build location settings. -->
  <PropertyGroup>
    <FreeDotnetProjectCategory>tests</FreeDotnetProjectCategory>
    <IsTestProject Condition="'$(IsTestProject)' == ''">true</IsTestProject>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet Condition="'$(CodeAnalysisRuleSet)' == ''">$(MSBuildThisFileDirectory)..\..\freedotnet.tests.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <!-- Package references and additional files which are consumed by test projects -->
  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <!-- Test tooling. The tests target net8.0 and net472; all versions below support both. -->
    <PackageReference Include="xunit" Version="2.9.3" IsImplicitlyDefined="true" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" IsImplicitlyDefined="true" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" IsImplicitlyDefined="true" />

    <PackageReference Include="coverlet.collector"
                      Version="6.0.4"
                      PrivateAssets="All"
                      IsImplicitlyDefined="true"
                      Condition="'$(IsCodeCoverage)'=='true'"/>
  </ItemGroup>

</Project>
